version: '3'

vars:
  PYTHON: "3.11"

tasks:

  dev:
    cmds:
      - task: uv-venv
      - task: uv-install

  uv-venv:
    cmds:
      - uv venv --python={{ .PYTHON }}
    silent: true

  uv-install:
    cmds:
      - uv pip install --upgrade .[bootstrap5,polymorphic,dev,test]
    silent: true

  uv-install-minimal:
    cmds:
      - uv pip install --upgrade .[minimal,bootstrap5minimal,polymorphic,dev,test]
    silent: true

  uv-build:
    cmds:
      - uv build
    silent: true

  uv-publish:
    cmds:
      - uv publish
    silent: true

  docs:
    cmds:
      - mkdocs serve -a localhost:8001
    silent: true


  upload:
    cmds:
      - twine upload -r pypi dist/*
    silent: true
