# Generated by Django 5.1.5 on 2025-02-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookbookrecipe",
            name="rec_ingredients",
            field=models.ManyToManyField(
                through="app.CookbookRecIng", to="app.cookbookingredient"
            ),
        ),
    ]
