name: Pipeline
run-name: ${{ github.actor }} triggered the pipeline
on: [push]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Create virtual environment and install requirements
        run: |
          uv venv --python=3.12
          uv pip install -r ${{ github.workspace }}/requirements/requirements-test.txt

      - name: Run the tests
        run: uv run nox

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: [tests]
    #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    environment:
      name: pypi
      url: https://test.pypi.org/p/django-crud-views
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      # retrieve your distributions here
      - run: echo "Publishing to PyPI..."
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            repository-url: https://test.pypi.org/legacy/
