name: Default Workflow
run-name: ${{ github.actor }} is running tests
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Create virtual environment and install requirements
        run: |
          uv venv --python=3.12
          uv pip install -r ${{ github.workspace }}/requirements/requirements-test.txt

      - name: Run the tests
        run: uv run nox

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    steps:
      - run: echo "Publishing to PyPI..."

