name: Run Tests
run-name: ${{ github.actor }} is running tests
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: |
          uv venv --python=3.10
          uv pip install -r ${{ github.workspace }}/requirements/requirements-test.txt

      - name: Run tests
        run: uv run nox
